apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ layer_name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ environment }}
  source:
    repoURL: https://github.com/OWNER/REPO.git
    targetRevision: HEAD
    path: {{ environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ environment }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
