import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      link: {
        type: 'doc',
        id: 'agents/overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'agents',
        },
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      link: {
        type: 'doc',
        id: 'skills/overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skills',
        },
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'doc',
        id: 'plugins/overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plugins',
        },
      ],
    },
    {
      type: 'category',
      label: 'Usage Guide',
      items: [
        'usage/commands',
        'usage/workflows',
        'usage/best-practices',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/design-principles',
        'architecture/model-tiers',
        'architecture/repository-structure',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/agent-format',
        'api/skill-format',
        'api/scripts',
      ],
    },
  ],
};

export default sidebars;
