apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ layer_name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/REPO.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ layer_name }}
  syncPolicy: {}
