apiVersion: katalyst.taxonomy/v1alpha
kind: TaxonomyNode
metadata:
  name: {{ layer_name }}
taxonomyNodeType: layer
spec:
  description: {{ description }}
  environments:
    - {{ primary_environment }}
  type: application
  layerType: app-docker
  parents:
    node: {{ parent_stack }}
  owners:
    - {{ owner_email }}
