region: us-east-1
assume_role: katalyst-cicd-bootstrap-prod
admin_role: eks-cluster-admin
permissions_boundary: prima-permissions-boundary-policy
domain_name: alvisprima.com
hosted_zone_id: PLACEHOLDER_PROD_HOSTED_ZONE_ID
